stages:
  - test


variables:
  GIT_STRATEGY: none
  GIT_REPO_URL: "http://gitlab:30080/${CI_PROJECT_PATH}.git"

test_job:
  stage: test
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - echo "Clonando repositório manualmente..."
    - git clone "$GIT_REPO_URL" .
    - echo "Ambiente OK"
    - uname -a