stages:
  - test

variables:
  GIT_REPO_URL: "http://gitlab:30080/${CI_PROJECT_PATH}.git"

test_job:
  stage: test
  script:
    - echo "Clonando repositório manualmente..."
    - rm -rf *
    - git clone "$GIT_REPO_URL" .
    - echo "Testando ambiente do runner"
    - uname -a