services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db_gateway
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_gateway:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .  # Assumindo que o Dockerfile está na raiz do projeto
    container_name: go_gateway_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gateway
      DB_SSLMODE: disable
      USE_ENV_FILE: false

volumes:
  postgres_data_gateway:
    driver: local